/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Korisnik;
import javax.swing.JOptionPane;
import kontroler.KontrolerKlijent;
import modeli.ModelTabelePretragaNastavnik;
import modeli.ModelTabelePretragaPredmet;

/**
 *
 * @author Luka
 */
public class GlavnaKlijentskaForma extends javax.swing.JFrame {
    
    private String ulogovaniKorisnik;
    
    

    /**
     * Creates new form GlavnaKlijentskaForma
     */
    public GlavnaKlijentskaForma() {
        initComponents();
        setLocationRelativeTo(null);
        srediComboBox();
        srediTabele();
        KontrolerKlijent.getInstance().setGkf(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelaUlogovaniKorisnik = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboVrstaPretrage = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtTerminPretrage = new javax.swing.JTextField();
        panelNastavnici = new javax.swing.JPanel();
        btnPretraziNastavnike = new javax.swing.JButton();
        btnPrikaziSveNastavnike = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaNastavnikPretraga = new javax.swing.JTable();
        btnPrikaziPodatkeOKlijentu = new javax.swing.JButton();
        btnDodajNovogNastavnika = new javax.swing.JButton();
        btnDodajReferencu = new javax.swing.JButton();
        panelPredmeti = new javax.swing.JPanel();
        btnPretraziPredmete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnPrikaziPodatkeOPredmetu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPredmetiPretraga = new javax.swing.JTable();
        btnDodajNoviPredmet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1208, 700));

        labelaUlogovaniKorisnik.setText("Ulogovani korisnik: ");

        jLabel1.setText("Vrsta pretrage:");

        comboVrstaPretrage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboVrstaPretrage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVrstaPretrageActionPerformed(evt);
            }
        });

        jLabel2.setText("Pretraga:");

        btnPretraziNastavnike.setText("Pretrazi nastavnike");
        btnPretraziNastavnike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziNastavnikeActionPerformed(evt);
            }
        });

        btnPrikaziSveNastavnike.setText("Prikazi sve nastavnike");
        btnPrikaziSveNastavnike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziSveNastavnikeActionPerformed(evt);
            }
        });

        tabelaNastavnikPretraga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaNastavnikPretraga);

        btnPrikaziPodatkeOKlijentu.setText("Prikazi podatke o izabranom nastavniku");
        btnPrikaziPodatkeOKlijentu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziPodatkeOKlijentuActionPerformed(evt);
            }
        });

        btnDodajNovogNastavnika.setText("Dodaj novog nastavnika");
        btnDodajNovogNastavnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajNovogNastavnikaActionPerformed(evt);
            }
        });

        btnDodajReferencu.setText("Dodaj novu referencu");
        btnDodajReferencu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajReferencuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNastavniciLayout = new javax.swing.GroupLayout(panelNastavnici);
        panelNastavnici.setLayout(panelNastavniciLayout);
        panelNastavniciLayout.setHorizontalGroup(
            panelNastavniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNastavniciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNastavniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelNastavniciLayout.createSequentialGroup()
                        .addComponent(btnPretraziNastavnike)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrikaziSveNastavnike)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrikaziPodatkeOKlijentu)
                        .addGap(18, 18, 18)
                        .addComponent(btnDodajNovogNastavnika)
                        .addGap(18, 18, 18)
                        .addComponent(btnDodajReferencu)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelNastavniciLayout.setVerticalGroup(
            panelNastavniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNastavniciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNastavniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPretraziNastavnike)
                    .addComponent(btnPrikaziSveNastavnike)
                    .addComponent(btnPrikaziPodatkeOKlijentu)
                    .addComponent(btnDodajNovogNastavnika)
                    .addComponent(btnDodajReferencu))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPretraziPredmete.setText("Pretrazi predmete");
        btnPretraziPredmete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziPredmeteActionPerformed(evt);
            }
        });

        jButton1.setText("Prikazi sve predmete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnPrikaziPodatkeOPredmetu.setText("Prikazi podatke o izabranom predmetu");
        btnPrikaziPodatkeOPredmetu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziPodatkeOPredmetuActionPerformed(evt);
            }
        });

        tabelaPredmetiPretraga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelaPredmetiPretraga);

        btnDodajNoviPredmet.setText("Dodaj novi predmet");
        btnDodajNoviPredmet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajNoviPredmetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPredmetiLayout = new javax.swing.GroupLayout(panelPredmeti);
        panelPredmeti.setLayout(panelPredmetiLayout);
        panelPredmetiLayout.setHorizontalGroup(
            panelPredmetiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPredmetiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPredmetiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(panelPredmetiLayout.createSequentialGroup()
                        .addComponent(btnPretraziPredmete)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrikaziPodatkeOPredmetu)
                        .addGap(18, 18, 18)
                        .addComponent(btnDodajNoviPredmet)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPredmetiLayout.setVerticalGroup(
            panelPredmetiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPredmetiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPredmetiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPretraziPredmete)
                    .addComponent(jButton1)
                    .addComponent(btnPrikaziPodatkeOPredmetu)
                    .addComponent(btnDodajNoviPredmet))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPredmeti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNastavnici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelaUlogovaniKorisnik)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(comboVrstaPretrage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtTerminPretrage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelaUlogovaniKorisnik)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboVrstaPretrage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTerminPretrage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelNastavnici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPredmeti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrikaziSveNastavnikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziSveNastavnikeActionPerformed
        KontrolerKlijent.getInstance().vratiSveNastavnike();
    }//GEN-LAST:event_btnPrikaziSveNastavnikeActionPerformed

    private void btnPretraziNastavnikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziNastavnikeActionPerformed
        String imePrezime = txtTerminPretrage.getText();
        KontrolerKlijent.getInstance().pretraziNastavnike(imePrezime);
    }//GEN-LAST:event_btnPretraziNastavnikeActionPerformed

    private void comboVrstaPretrageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVrstaPretrageActionPerformed
        String kategorija = (String) comboVrstaPretrage.getSelectedItem();
        if (kategorija == "Nastavnik") {
            panelNastavnici.setVisible(true);
            panelPredmeti.setVisible(false);
        } else {
            panelNastavnici.setVisible(false);
            panelPredmeti.setVisible(true);
        }
    }//GEN-LAST:event_comboVrstaPretrageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        KontrolerKlijent.getInstance().vratiSvePredmete();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPretraziPredmeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziPredmeteActionPerformed
        String nazivPredmeta = txtTerminPretrage.getText();
        KontrolerKlijent.getInstance().pretraziPredmete(nazivPredmeta);
    }//GEN-LAST:event_btnPretraziPredmeteActionPerformed

    private void btnPrikaziPodatkeOPredmetuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziPodatkeOPredmetuActionPerformed
        int row = tabelaPredmetiPretraga.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Morate izabrati predmet!");
        } else {
            KontrolerKlijent.getInstance().vratiPodatkeOPredmetu(KontrolerKlijent.getInstance().getListaPredmetaPretraga().get(row));
        }
    }//GEN-LAST:event_btnPrikaziPodatkeOPredmetuActionPerformed

    private void btnPrikaziPodatkeOKlijentuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziPodatkeOKlijentuActionPerformed
        int row = tabelaNastavnikPretraga.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Morate izabrati nastavnika!");
        } else {
            KontrolerKlijent.getInstance().vratiPodatkeONastavniku(KontrolerKlijent.getInstance().getListaNastavnikaPretraga().get(row));
        }
    }//GEN-LAST:event_btnPrikaziPodatkeOKlijentuActionPerformed

    private void btnDodajNovogNastavnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajNovogNastavnikaActionPerformed
        KontrolerKlijent.getInstance().vratiSveTipoveNastavnika("glavnaKlijentForma");
    }//GEN-LAST:event_btnDodajNovogNastavnikaActionPerformed

    private void btnDodajNoviPredmetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajNoviPredmetActionPerformed
        KontrolerKlijent.getInstance().vratiSveStudijskePrograme("glavnaKlijentForma");
    }//GEN-LAST:event_btnDodajNoviPredmetActionPerformed

    private void btnDodajReferencuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajReferencuActionPerformed
        KontrolerKlijent.getInstance().dodajNovuReferencu();
    }//GEN-LAST:event_btnDodajReferencuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaKlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaKlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajNoviPredmet;
    private javax.swing.JButton btnDodajNovogNastavnika;
    private javax.swing.JButton btnDodajReferencu;
    private javax.swing.JButton btnPretraziNastavnike;
    private javax.swing.JButton btnPretraziPredmete;
    private javax.swing.JButton btnPrikaziPodatkeOKlijentu;
    private javax.swing.JButton btnPrikaziPodatkeOPredmetu;
    private javax.swing.JButton btnPrikaziSveNastavnike;
    private javax.swing.JComboBox<String> comboVrstaPretrage;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelaUlogovaniKorisnik;
    private javax.swing.JPanel panelNastavnici;
    private javax.swing.JPanel panelPredmeti;
    private javax.swing.JTable tabelaNastavnikPretraga;
    private javax.swing.JTable tabelaPredmetiPretraga;
    private javax.swing.JTextField txtTerminPretrage;
    // End of variables declaration//GEN-END:variables

    private void srediTabele() {
        ModelTabelePretragaNastavnik mtp = new ModelTabelePretragaNastavnik();
        mtp.setForma("glavnaKlijentForma");
        tabelaNastavnikPretraga.setModel(mtp);
        ModelTabelePretragaPredmet mtpp = new ModelTabelePretragaPredmet();
        tabelaPredmetiPretraga.setModel(mtpp);
    }

    private void srediComboBox() {
        comboVrstaPretrage.removeAllItems();
        comboVrstaPretrage.addItem("Nastavnik");
        comboVrstaPretrage.addItem("Predmet");
    }

    public String getUlogovaniKorisnik() {
        return ulogovaniKorisnik;
    }

    public void setUlogovaniKorisnik(String ulogovaniKorisnik) {
        this.ulogovaniKorisnik = ulogovaniKorisnik;
    }

    void postaviUlogovanogKorisnika(String ulogovaniKorisnik) {
        setUlogovaniKorisnik(ulogovaniKorisnik);
        labelaUlogovaniKorisnik.setText("Ulogovani korisnik: " + ulogovaniKorisnik);
    }

    public void ugasiAplikaciju() {
        JOptionPane.showMessageDialog(this, "Server vas je izbacio!");
        KontrolerKlijent.getInstance().ugasiAplikaciju();
    }

    public void osveziTabeluNastavnika() {
        ModelTabelePretragaNastavnik mtp = (ModelTabelePretragaNastavnik) tabelaNastavnikPretraga.getModel();
        mtp.fireTableDataChanged();
    }

    public void osveziTabeluPredmeta() {
        ModelTabelePretragaPredmet mtpp = (ModelTabelePretragaPredmet) tabelaPredmetiPretraga.getModel();
        mtpp.fireTableDataChanged();
    }

    
}
