/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Nastavnik;
import javax.swing.JOptionPane;
import kontroler.KontrolerKlijent;
import modeli.ModelTabeleAkademskiUspeh;
import modeli.ModelTabelePredmetiNastavnika;
import modeli.ModelTabeleReference;
import modeli.ModelTabeleUsavrsavanja;

/**
 *
 * @author Luka
 */
public class GlavnaNastavnikForma extends javax.swing.JFrame {

    private Nastavnik nastavnik;
    
    /**
     * Creates new form GlavnaNastavnikForma
     */
    public GlavnaNastavnikForma() {
        initComponents();
        setLocationRelativeTo(null);
        inicijalizujTabele();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelaImePrezime = new javax.swing.JLabel();
        labelaInstitucija = new javax.swing.JLabel();
        labelaNaucnaOblast = new javax.swing.JLabel();
        labelaTipNastavnika = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAkademskaKarijera = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPredmeti = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaReference = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaUsavrsavanja = new javax.swing.JTable();
        btnNazad = new javax.swing.JButton();
        btnObrisiNastavnika = new javax.swing.JButton();
        btnIzmeniNastavnika = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelaImePrezime.setText("Ime i prezime:");

        labelaInstitucija.setText("Institucija:");

        labelaNaucnaOblast.setText("Naucna oblast:");

        labelaTipNastavnika.setText("Tip nastavnika:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Akademska karijera"));

        tabelaAkademskaKarijera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaAkademskaKarijera);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Predmeti"));

        tabelaPredmeti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelaPredmeti);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Reference"));

        tabelaReference.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelaReference);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Usavrsavanja"));

        tabelaUsavrsavanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabelaUsavrsavanja);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        btnObrisiNastavnika.setText("Obrisi nastavnika");
        btnObrisiNastavnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiNastavnikaActionPerformed(evt);
            }
        });

        btnIzmeniNastavnika.setText("Izmeni nastavnika");
        btnIzmeniNastavnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniNastavnikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelaNaucnaOblast)
                            .addComponent(labelaTipNastavnika)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelaImePrezime)
                                    .addComponent(labelaInstitucija))
                                .addGap(233, 233, 233)
                                .addComponent(btnIzmeniNastavnika)
                                .addGap(18, 18, 18)
                                .addComponent(btnObrisiNastavnika)
                                .addGap(18, 18, 18)
                                .addComponent(btnNazad)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelaImePrezime)
                        .addGap(15, 15, 15)
                        .addComponent(labelaInstitucija))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNazad)
                            .addComponent(btnObrisiNastavnika)
                            .addComponent(btnIzmeniNastavnika))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelaNaucnaOblast)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelaTipNastavnika)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        KontrolerKlijent.getInstance().prikaziGlavnuKlijentFormu("glavnaNastavnikForma");
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnObrisiNastavnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiNastavnikaActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete nastavnika?", "Brisanje predmeta", JOptionPane.YES_NO_OPTION) == 0) {
            KontrolerKlijent.getInstance().obrisiNastavnika(nastavnik);
        }
    }//GEN-LAST:event_btnObrisiNastavnikaActionPerformed

    private void btnIzmeniNastavnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniNastavnikaActionPerformed
        KontrolerKlijent.getInstance().prikaziFormuZaIzmenuNastavnika(nastavnik);
    }//GEN-LAST:event_btnIzmeniNastavnikaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaNastavnikForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaNastavnikForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaNastavnikForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaNastavnikForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaNastavnikForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniNastavnika;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnObrisiNastavnika;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelaImePrezime;
    private javax.swing.JLabel labelaInstitucija;
    private javax.swing.JLabel labelaNaucnaOblast;
    private javax.swing.JLabel labelaTipNastavnika;
    private javax.swing.JTable tabelaAkademskaKarijera;
    private javax.swing.JTable tabelaPredmeti;
    private javax.swing.JTable tabelaReference;
    private javax.swing.JTable tabelaUsavrsavanja;
    // End of variables declaration//GEN-END:variables

    public Nastavnik getNastavnik() {
        return nastavnik;
    }

    public void setNastavnik(Nastavnik nastavnik) {
        this.nastavnik = nastavnik;
    }

    public void podesiFormu() {
        labelaImePrezime.setText("Ime i prezime: " + nastavnik.getImePrezime());
        labelaTipNastavnika.setText("Tip nastavnika: " + nastavnik.getTipNastavnika().getNaziv());
        labelaInstitucija.setText("Institucija: " + nastavnik.getInstitucija());
        labelaNaucnaOblast.setText("Naucna oblast: " + nastavnik.getNaucnaOblast());
        
        osveziTabele();
        
    }

    private void inicijalizujTabele() {
        ModelTabeleAkademskiUspeh modelTabeleAkademskiUspeh = new ModelTabeleAkademskiUspeh();
        ModelTabelePredmetiNastavnika modelTabelePredmetiNastavnika = new ModelTabelePredmetiNastavnika();
        ModelTabeleReference modelTabeleReference = new ModelTabeleReference();
        ModelTabeleUsavrsavanja modelTabeleUsavrsavanja = new ModelTabeleUsavrsavanja();
        
        tabelaAkademskaKarijera.setModel(modelTabeleAkademskiUspeh);
        tabelaPredmeti.setModel(modelTabelePredmetiNastavnika);
        tabelaReference.setModel(modelTabeleReference);
        tabelaUsavrsavanja.setModel(modelTabeleUsavrsavanja);
    }

    private void osveziTabele() {
        ModelTabeleAkademskiUspeh modelTabeleAkademskiUspeh = (ModelTabeleAkademskiUspeh) tabelaAkademskaKarijera.getModel();
        ModelTabelePredmetiNastavnika modelTabelePredmetiNastavnika = (ModelTabelePredmetiNastavnika) tabelaPredmeti.getModel();
        ModelTabeleReference modelTabeleReference = (ModelTabeleReference) tabelaReference.getModel();
        ModelTabeleUsavrsavanja modelTabeleUsavrsavanja = (ModelTabeleUsavrsavanja) tabelaUsavrsavanja.getModel();
        
        modelTabeleAkademskiUspeh.fireTableDataChanged();
        modelTabelePredmetiNastavnika.fireTableDataChanged();
        modelTabeleReference.fireTableDataChanged();
        modelTabeleUsavrsavanja.fireTableDataChanged();
    }

    public void uspesnoObrisanNastavnik(boolean uspesnoObrisanNastavnik) {
        if (uspesnoObrisanNastavnik) {
            JOptionPane.showMessageDialog(this, "Uspesno obrisan nastavnik iz baze!");
            KontrolerKlijent.getInstance().prikaziGlavnuKlijentFormu("glavnaNastavnikForma");
        } else {
            JOptionPane.showMessageDialog(this, "Greska prilikom brisanja nastavnika iz baze!");
        }
    }
}
