/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.AkademskiUspeh;
import domen.Nastavnik;
import domen.Predaje;
import domen.Predmet;
import domen.Referenca;
import domen.TipNastavnika;
import domen.TipUspeha;
import domen.Usavrsavanje;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import kontroler.KontrolerKlijent;
import modeli.ModelTabeleAkademskiUspeh;
import modeli.ModelTabelePredaje;
import modeli.ModelTabelePretragaPredmet;
import modeli.ModelTabeleReference;
import modeli.ModelTabeleUsavrsavanja;

/**
 *
 * @author Luka
 */
public class UnosNovogNastavnikaForma extends javax.swing.JFrame {

    private Nastavnik nastavnik;
    private List<Referenca> listaReferenciPretraga;
    private List<Predmet> listaPredmetaPretraga;
    private List<TipNastavnika> listaTipovaNastavnika;
    private List<TipUspeha> listaTipovaUspeha;

    /**
     * Creates new form UnosNovogNastavnikaForma
     */
    public UnosNovogNastavnikaForma() {
        initComponents();
        setLocationRelativeTo(null);
        nastavnik = new Nastavnik();
        inicijalizujListe();
        inicijalizujTabele();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNaucnaOblast = new javax.swing.JTextField();
        txtInstitucija = new javax.swing.JTextField();
        txtImePrezime = new javax.swing.JTextField();
        comboTipNastavnika = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNazivInstitucijeUsavrsavanja = new javax.swing.JTextField();
        txtNazivUsavrsavanja = new javax.swing.JTextField();
        txtGodinaUsavrsavanja = new javax.swing.JTextField();
        btnDodajUsavrsavanje = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsavrsavanja = new javax.swing.JTable();
        btnIzbaciUsavrsavanje = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        comboTipUspeha = new javax.swing.JComboBox();
        txtGodinaUspeha = new javax.swing.JTextField();
        txtInstitucijaUspeha = new javax.swing.JTextField();
        txtOblastUspeha = new javax.swing.JTextField();
        btnDodajUspeh = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaAkademskiUspesi = new javax.swing.JTable();
        btnIzbaciUspeh = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtNaslovReference = new javax.swing.JTextField();
        btnPretraziReference = new javax.swing.JButton();
        btnPrikaziSveReference = new javax.swing.JButton();
        btnDodajReferencu = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaPronadjeneReference = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelaDodateReference = new javax.swing.JTable();
        btnIzbaciReferencu = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtNazivPredmeta = new javax.swing.JTextField();
        btnPretraziPredmete = new javax.swing.JButton();
        btnPrikaziSvePredmete = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtBrojCasova = new javax.swing.JTextField();
        btnDodajPredmet = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelaPronadjeniPredmeti = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelaDodatiPredmeti = new javax.swing.JTable();
        btnIzbaciPredmet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 800));

        jScrollPane4.setBorder(null);
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos novog nastavnika"));

        jLabel1.setText("Ime i prezime:");

        jLabel2.setText("Institucija:");

        jLabel3.setText("Naucna oblast:");

        jLabel4.setText("Tip nastavnika:");

        comboTipNastavnika.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Usavrsavanje"));

        jLabel5.setText("Naziv:");

        jLabel6.setText("Institucija:");

        jLabel7.setText("Godina:");

        btnDodajUsavrsavanje.setText("Dodaj usavrsavanje");
        btnDodajUsavrsavanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajUsavrsavanjeActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dodata usavrsavanja"));

        tabelaUsavrsavanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaUsavrsavanja);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnIzbaciUsavrsavanje.setText("Izbaci");
        btnIzbaciUsavrsavanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbaciUsavrsavanjeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGodinaUsavrsavanja, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtNazivInstitucijeUsavrsavanja, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNazivUsavrsavanja, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(btnDodajUsavrsavanje)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzbaciUsavrsavanje)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNazivUsavrsavanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNazivInstitucijeUsavrsavanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtGodinaUsavrsavanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDodajUsavrsavanje)
                    .addComponent(btnIzbaciUsavrsavanje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Akademski uspeh"));

        jLabel8.setText("Tip uspeha:");

        jLabel9.setText("Godina:");

        jLabel10.setText("Institucija:");

        jLabel11.setText("Oblast:");

        comboTipUspeha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnDodajUspeh.setText("Dodaj uspeh");
        btnDodajUspeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajUspehActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Dodati akademski uspesi"));

        tabelaAkademskiUspesi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelaAkademskiUspesi);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnIzbaciUspeh.setText("Izbaci");
        btnIzbaciUspeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbaciUspehActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGodinaUspeha)
                            .addComponent(txtInstitucijaUspeha)
                            .addComponent(txtOblastUspeha)
                            .addComponent(comboTipUspeha, 0, 300, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnDodajUspeh)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzbaciUspeh)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboTipUspeha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtGodinaUspeha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtInstitucijaUspeha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtOblastUspeha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDodajUspeh)
                    .addComponent(btnIzbaciUspeh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Reference"));

        jLabel12.setText("Naslov:");

        btnPretraziReference.setText("Pretrazi");
        btnPretraziReference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziReferenceActionPerformed(evt);
            }
        });

        btnPrikaziSveReference.setText("Prikazi sve");
        btnPrikaziSveReference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziSveReferenceActionPerformed(evt);
            }
        });

        btnDodajReferencu.setText("Dodaj");
        btnDodajReferencu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajReferencuActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Pronadjene reference"));

        tabelaPronadjeneReference.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelaPronadjeneReference);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Dodate reference"));

        tabelaDodateReference.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tabelaDodateReference);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnIzbaciReferencu.setText("Izbaci");
        btnIzbaciReferencu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbaciReferencuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txtNaslovReference, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPretraziReference)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrikaziSveReference)
                        .addGap(18, 18, 18)
                        .addComponent(btnDodajReferencu))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzbaciReferencu)
                        .addGap(629, 629, 629))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNaslovReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraziReference)
                    .addComponent(btnPrikaziSveReference)
                    .addComponent(btnDodajReferencu)
                    .addComponent(btnIzbaciReferencu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSacuvaj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Predmeti"));

        jLabel13.setText("Naziv predmeta:");

        btnPretraziPredmete.setText("Pretrazi");
        btnPretraziPredmete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziPredmeteActionPerformed(evt);
            }
        });

        btnPrikaziSvePredmete.setText("Prikazi sve");
        btnPrikaziSvePredmete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziSvePredmeteActionPerformed(evt);
            }
        });

        jLabel14.setText("Broj casova nedeljno:");

        btnDodajPredmet.setText("Dodaj");
        btnDodajPredmet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajPredmetActionPerformed(evt);
            }
        });

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Pronadjeni predmeti"));

        tabelaPronadjeniPredmeti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tabelaPronadjeniPredmeti);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Dodati predmeti"));

        tabelaDodatiPredmeti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tabelaDodatiPredmeti);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnIzbaciPredmet.setText("Izbaci");
        btnIzbaciPredmet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbaciPredmetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txtBrojCasova, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDodajPredmet))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtNazivPredmeta, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPretraziPredmete)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrikaziSvePredmete)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzbaciPredmet))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNazivPredmeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraziPredmete)
                    .addComponent(btnPrikaziSvePredmete)
                    .addComponent(btnIzbaciPredmet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtBrojCasova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDodajPredmet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(17, 17, 17)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(comboTipNastavnika, 0, 300, Short.MAX_VALUE)
                            .addComponent(txtInstitucija, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtImePrezime, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNaucnaOblast, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnNazad, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 502, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtInstitucija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtNaucnaOblast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboTipNastavnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNazad, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(361, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1204, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        KontrolerKlijent.getInstance().setTrenutnaForma("");
        KontrolerKlijent.getInstance().prikaziGlavnuKlijentFormu("unosNastavnikaForma");
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnDodajUsavrsavanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajUsavrsavanjeActionPerformed
        String naziv = txtNazivUsavrsavanja.getText();
        String institucija = txtNazivInstitucijeUsavrsavanja.getText();
        String godinaString = txtGodinaUsavrsavanja.getText();
        int godina = 0;
        try {
            godina = Integer.parseInt(godinaString);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Godina mora biti broj!");
            return;
        }

        
        
        if (godina < 0) {
            JOptionPane.showMessageDialog(this, "Godina mora biti veca od 0!");
            return;
        }
        if (naziv.equals("") || institucija.equals("")) {
            JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!");
        } else {
            nastavnik.getListaUsavrsavanja().add(new Usavrsavanje(0, naziv, institucija, godina, nastavnik));
            osveziTabele();

        }

    }//GEN-LAST:event_btnDodajUsavrsavanjeActionPerformed

    private void btnDodajUspehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajUspehActionPerformed
        TipUspeha tip = (TipUspeha) comboTipUspeha.getSelectedItem();
        String institucija = txtInstitucijaUspeha.getText();
        String godinaString = txtGodinaUspeha.getText();
        String oblast = txtOblastUspeha.getText();
        int godina = 0;
        try {
            godina = Integer.parseInt(godinaString);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Godina mora biti broj!");
            return;
        }
        
        if (godina < 0) {
            JOptionPane.showMessageDialog(this, "Godina mora biti veca od 0!");
            return;
        }

        if (oblast.equals("") || institucija.equals("")) {
            JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!");
        } else {
            nastavnik.getListaAkademskihUspeha().add(new AkademskiUspeh(0, godina, institucija, oblast, tip, nastavnik));
            osveziTabele();

        }

    }//GEN-LAST:event_btnDodajUspehActionPerformed

    private void btnPretraziPredmeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziPredmeteActionPerformed
        String nazivPredmeta = txtNazivPredmeta.getText();
        KontrolerKlijent.getInstance().pretraziPredmete(nazivPredmeta);
    }//GEN-LAST:event_btnPretraziPredmeteActionPerformed

    private void btnPrikaziSvePredmeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziSvePredmeteActionPerformed
        KontrolerKlijent.getInstance().pretraziPredmete("");
    }//GEN-LAST:event_btnPrikaziSvePredmeteActionPerformed

    private void btnDodajPredmetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajPredmetActionPerformed
        int row = tabelaPronadjeniPredmeti.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Morate izabrati predmet!");
        } else {
            Predmet predmet = listaPredmetaPretraga.get(row);
            String brojCasovaString = txtBrojCasova.getText();
            int brojCasova = 0;
            try {
                brojCasova = Integer.parseInt(brojCasovaString);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Broj casova mora biti broj!");
                return;
            }
            if (brojCasova < 0) {
                JOptionPane.showMessageDialog(this, "Broj casova mora biti veci od 0!");
                return;
            }

            if (!sadrziPredmet(predmet)) {
                nastavnik.getListaPredavanja().add(new Predaje(nastavnik, predmet, brojCasova));
            } else {
                JOptionPane.showMessageDialog(this, "Predmet je vec dodat!");
            }

            osveziTabele();
        }
    }//GEN-LAST:event_btnDodajPredmetActionPerformed

    private void btnIzbaciPredmetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbaciPredmetActionPerformed
        int row = tabelaDodatiPredmeti.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Morate izabrati predmet!");
        } else {
            nastavnik.getListaPredavanja().remove(row);
            osveziTabele();
        }
    }//GEN-LAST:event_btnIzbaciPredmetActionPerformed

    private void btnPretraziReferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziReferenceActionPerformed
        String naslov = txtNaslovReference.getText();
        KontrolerKlijent.getInstance().pretraziReference(naslov, "unosNastavnikaForma");
    }//GEN-LAST:event_btnPretraziReferenceActionPerformed

    private void btnIzbaciReferencuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbaciReferencuActionPerformed
        int row = tabelaDodateReference.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Morate izabrati referencu!");
        } else {
            nastavnik.getListaReferenci().remove(row);
            osveziTabele();
        }
    }//GEN-LAST:event_btnIzbaciReferencuActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        String imePrezime = txtImePrezime.getText();
        String institucija = txtInstitucija.getText();
        String naucnaOblast = txtNaucnaOblast.getText();
        TipNastavnika tipNastavnika = (TipNastavnika) comboTipNastavnika.getSelectedItem();

        if (!imePrezime.equals("") || !institucija.equals("") || !naucnaOblast.equals("")) {
            nastavnik.setImePrezime(imePrezime);
            nastavnik.setInstitucija(institucija);
            nastavnik.setNaucnaOblast(naucnaOblast);
            nastavnik.setTipNastavnika(tipNastavnika);
            
            KontrolerKlijent.getInstance().unesiNastavnika(nastavnik);
            
        } else {
            JOptionPane.showMessageDialog(this, "Svi licni podaci o nastavniku moraju biti uneti!");
        }


    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnDodajReferencuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajReferencuActionPerformed
        int row = tabelaPronadjeneReference.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Morate izabrati referencu!");
        } else {
            Referenca referenca = listaReferenciPretraga.get(row);
            if (!sadrziReferencu(referenca)) {
                nastavnik.getListaReferenci().add(referenca);
                osveziTabele();
            } else {
                JOptionPane.showMessageDialog(this, "Referenca je vec dodata!");
            }
        }
    }//GEN-LAST:event_btnDodajReferencuActionPerformed

    private void btnPrikaziSveReferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziSveReferenceActionPerformed
        KontrolerKlijent.getInstance().pretraziReference("", "unosNastavnikaForma");
    }//GEN-LAST:event_btnPrikaziSveReferenceActionPerformed

    private void btnIzbaciUsavrsavanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbaciUsavrsavanjeActionPerformed
        int row = tabelaUsavrsavanja.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Morate izabrati usavrsavanje!");
        } else {
            nastavnik.getListaUsavrsavanja().remove(row);
            osveziTabele();
        }
    }//GEN-LAST:event_btnIzbaciUsavrsavanjeActionPerformed

    private void btnIzbaciUspehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbaciUspehActionPerformed
        int row = tabelaAkademskiUspesi.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Morate izabrati akademski uspeh!");
        } else {
            nastavnik.getListaAkademskihUspeha().remove(row);
            osveziTabele();
        }
    }//GEN-LAST:event_btnIzbaciUspehActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnosNovogNastavnikaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnosNovogNastavnikaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnosNovogNastavnikaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnosNovogNastavnikaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnosNovogNastavnikaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajPredmet;
    private javax.swing.JButton btnDodajReferencu;
    private javax.swing.JButton btnDodajUsavrsavanje;
    private javax.swing.JButton btnDodajUspeh;
    private javax.swing.JButton btnIzbaciPredmet;
    private javax.swing.JButton btnIzbaciReferencu;
    private javax.swing.JButton btnIzbaciUsavrsavanje;
    private javax.swing.JButton btnIzbaciUspeh;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnPretraziPredmete;
    private javax.swing.JButton btnPretraziReference;
    private javax.swing.JButton btnPrikaziSvePredmete;
    private javax.swing.JButton btnPrikaziSveReference;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox comboTipNastavnika;
    private javax.swing.JComboBox comboTipUspeha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable tabelaAkademskiUspesi;
    private javax.swing.JTable tabelaDodateReference;
    private javax.swing.JTable tabelaDodatiPredmeti;
    private javax.swing.JTable tabelaPronadjeneReference;
    private javax.swing.JTable tabelaPronadjeniPredmeti;
    private javax.swing.JTable tabelaUsavrsavanja;
    private javax.swing.JTextField txtBrojCasova;
    private javax.swing.JTextField txtGodinaUsavrsavanja;
    private javax.swing.JTextField txtGodinaUspeha;
    private javax.swing.JTextField txtImePrezime;
    private javax.swing.JTextField txtInstitucija;
    private javax.swing.JTextField txtInstitucijaUspeha;
    private javax.swing.JTextField txtNaslovReference;
    private javax.swing.JTextField txtNaucnaOblast;
    private javax.swing.JTextField txtNazivInstitucijeUsavrsavanja;
    private javax.swing.JTextField txtNazivPredmeta;
    private javax.swing.JTextField txtNazivUsavrsavanja;
    private javax.swing.JTextField txtOblastUspeha;
    // End of variables declaration//GEN-END:variables

    public Nastavnik getNastavnik() {
        return nastavnik;
    }

    public void setNastavnik(Nastavnik nastavnik) {
        this.nastavnik = nastavnik;
    }

    private void inicijalizujTabele() {
        ModelTabeleAkademskiUspeh modelTabeleAkademskiUspeh = new ModelTabeleAkademskiUspeh();
        modelTabeleAkademskiUspeh.setForma("unosNastavnikaForma");
        tabelaAkademskiUspesi.setModel(modelTabeleAkademskiUspeh);

        ModelTabeleUsavrsavanja modelTabeleUsavrsavanja = new ModelTabeleUsavrsavanja();
        modelTabeleUsavrsavanja.setForma("unosNastavnikaForma");
        tabelaUsavrsavanja.setModel(modelTabeleUsavrsavanja);

        ModelTabeleReference modelTabeleReferencePretraga = new ModelTabeleReference();
        modelTabeleReferencePretraga.setForma("unosNastavnikaFormaPretraga");
        tabelaPronadjeneReference.setModel(modelTabeleReferencePretraga);

        ModelTabeleReference modelTabeleReferenceNastavnik = new ModelTabeleReference();
        modelTabeleReferenceNastavnik.setForma("unosNastavnikaFormaNastavnik");
        tabelaDodateReference.setModel(modelTabeleReferenceNastavnik);

        ModelTabelePretragaPredmet modelTabelePretragaPredmetPretraga = new ModelTabelePretragaPredmet();
        modelTabelePretragaPredmetPretraga.setForma("unosNastavnikaForma");
        tabelaPronadjeniPredmeti.setModel(modelTabelePretragaPredmetPretraga);

        ModelTabelePredaje modelTabelePredaje = new ModelTabelePredaje();
        modelTabelePredaje.setForma("unosNastavnikaForma");
        tabelaDodatiPredmeti.setModel(modelTabelePredaje);

    }

    private void inicijalizujListe() {
        listaReferenciPretraga = new ArrayList<>();
        listaPredmetaPretraga = new ArrayList<>();
        listaTipovaNastavnika = new ArrayList<>();
        listaTipovaUspeha = new ArrayList<>();
    }

    public List<Referenca> getListaReferenciPretraga() {
        return listaReferenciPretraga;
    }

    public void setListaReferenciPretraga(List<Referenca> listaReferenciPretraga) {
        this.listaReferenciPretraga = listaReferenciPretraga;
    }

    public List<Predmet> getListaPredmetaPretraga() {
        return listaPredmetaPretraga;
    }

    public void setListaPredmetaPretraga(List<Predmet> listaPredmetaPretraga) {
        this.listaPredmetaPretraga = listaPredmetaPretraga;
    }

    public List<TipNastavnika> getListaTipovaNastavnika() {
        return listaTipovaNastavnika;
    }

    public void setListaTipovaNastavnika(List<TipNastavnika> listaTipovaNastavnika) {
        this.listaTipovaNastavnika = listaTipovaNastavnika;
    }

    public List<TipUspeha> getListaTipovaUspeha() {
        return listaTipovaUspeha;
    }

    public void setListaTipovaUspeha(List<TipUspeha> listaTipovaUspeha) {
        this.listaTipovaUspeha = listaTipovaUspeha;
    }

    public void podesiFormu() {
        comboTipNastavnika.removeAllItems();
        comboTipUspeha.removeAllItems();

        for (TipNastavnika tipNastavnika : listaTipovaNastavnika) {
            comboTipNastavnika.addItem(tipNastavnika);
        }

        for (TipUspeha tipUspeha : listaTipovaUspeha) {
            comboTipUspeha.addItem(tipUspeha);
        }
    }

    public void osveziTabele() {
        ModelTabeleAkademskiUspeh modelTabeleAkademskiUspeh = (ModelTabeleAkademskiUspeh) tabelaAkademskiUspesi.getModel();
        modelTabeleAkademskiUspeh.fireTableDataChanged();

        ModelTabeleUsavrsavanja modelTabeleUsavrsavanja = (ModelTabeleUsavrsavanja) tabelaUsavrsavanja.getModel();
        modelTabeleUsavrsavanja.fireTableDataChanged();

        ModelTabeleReference modelTabeleReferencePretraga = (ModelTabeleReference) tabelaPronadjeneReference.getModel();
        modelTabeleReferencePretraga.fireTableDataChanged();

        ModelTabeleReference modelTabeleReferenceNastavnik = (ModelTabeleReference) tabelaDodateReference.getModel();
        modelTabeleReferenceNastavnik.fireTableDataChanged();

        ModelTabelePretragaPredmet modelTabelePretragaPredmetPretraga = (ModelTabelePretragaPredmet) tabelaPronadjeniPredmeti.getModel();
        modelTabelePretragaPredmetPretraga.fireTableDataChanged();

        ModelTabelePredaje modelTabelePredaje = (ModelTabelePredaje) tabelaDodatiPredmeti.getModel();
        modelTabelePredaje.fireTableDataChanged();

    }

    private boolean sadrziPredmet(Predmet predmet) {
        for (Predaje predaje : nastavnik.getListaPredavanja()) {
            if (predaje.getPredmet().getPredmetID() == predmet.getPredmetID()) {
                return true;
            }
        }
        return false;
    }

    private boolean sadrziReferencu(Referenca referenca) {
        for (Referenca r : nastavnik.getListaReferenci()) {
            if (r.getReferencaID() == referenca.getReferencaID()) {
                return true;
            }
        }
        return false;
    }

    public void uspesnoUnetNastavnik(boolean uspesnoUnetNastavnik) {
        if (uspesnoUnetNastavnik) {
            JOptionPane.showMessageDialog(this, "Uspesno unet nastavnik u bazu.");
        } else {
            JOptionPane.showMessageDialog(this, "Greska prilikom unosa nastavnika u bazu.");
        }
    }

}
