/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Nastavnik;
import domen.Referenca;
import domen.SpoljniAutor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import kontroler.KontrolerKlijent;
import modeli.ModelTabelePretragaNastavnik;
import modeli.ModelTabeleSpoljniAutor;

/**
 *
 * @author Luka
 */
public class UnosNoveReferenceForma extends javax.swing.JFrame {

    private List<Nastavnik> listaNastavnikaPretraga;
    private List<SpoljniAutor> listaAutoraPretraga;
    private Referenca referenca;

    public Referenca getReferenca() {
        return referenca;
    }

    public void setReferenca(Referenca referenca) {
        this.referenca = referenca;
    }

    public List<Nastavnik> getListaNastavnikaPretraga() {
        return listaNastavnikaPretraga;
    }

    public void setListaNastavnikaPretraga(List<Nastavnik> listaNastavnikaPretraga) {
        this.listaNastavnikaPretraga = listaNastavnikaPretraga;
    }

    public List<SpoljniAutor> getListaAutoraPretraga() {
        return listaAutoraPretraga;
    }

    public void setListaAutoraPretraga(List<SpoljniAutor> listaAutoraPretraga) {
        this.listaAutoraPretraga = listaAutoraPretraga;
    }

    /**
     * Creates new form UnosNoveReferenceForma
     */
    public UnosNoveReferenceForma() {
        initComponents();
        setLocationRelativeTo(null);
        referenca = new Referenca();
        inicijalizujListe();
        inicijalizujTabele();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNaslov = new javax.swing.JTextField();
        txtGodina = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPretragaNastavnika = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtImePrezimeNastavnika = new javax.swing.JTextField();
        btnPretraziNastavnike = new javax.swing.JButton();
        btnPrikaziSveNastavnike = new javax.swing.JButton();
        btnDodajNastavnika = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaDodatiNastavnici = new javax.swing.JTable();
        btnIzbaciNastavnika = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaPretragaAutora = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtImePrezimeAutora = new javax.swing.JTextField();
        btnPretraziAutore = new javax.swing.JButton();
        btnPrikaziSveAutore = new javax.swing.JButton();
        btnDodajAutora = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelaDodatiAutori = new javax.swing.JTable();
        btnIzbaciAutora = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos nove reference"));

        jLabel1.setText("Naslov:");

        jLabel2.setText("Godina:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nastavnici"));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretraga nastavnika"));

        tabelaPretragaNastavnika.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelaPretragaNastavnika);

        jLabel3.setText("Ime i prezime:");

        btnPretraziNastavnike.setText("Pretrazi");
        btnPretraziNastavnike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziNastavnikeActionPerformed(evt);
            }
        });

        btnPrikaziSveNastavnike.setText("Prikazi sve");
        btnPrikaziSveNastavnike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziSveNastavnikeActionPerformed(evt);
            }
        });

        btnDodajNastavnika.setText("Dodaj");
        btnDodajNastavnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajNastavnikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImePrezimeNastavnika, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPretraziNastavnike)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrikaziSveNastavnike)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDodajNastavnika)
                        .addGap(0, 129, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtImePrezimeNastavnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraziNastavnike)
                    .addComponent(btnPrikaziSveNastavnike)
                    .addComponent(btnDodajNastavnika))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Dodati nastavnici"));

        tabelaDodatiNastavnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelaDodatiNastavnici);

        btnIzbaciNastavnika.setText("Izbaci");
        btnIzbaciNastavnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbaciNastavnikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnIzbaciNastavnika)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIzbaciNastavnika)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Spoljni autori"));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretraga autora"));

        tabelaPretragaAutora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabelaPretragaAutora);

        jLabel4.setText("Ime i prezime:");

        btnPretraziAutore.setText("Pretrazi");
        btnPretraziAutore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziAutoreActionPerformed(evt);
            }
        });

        btnPrikaziSveAutore.setText("Prikazi sve");
        btnPrikaziSveAutore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziSveAutoreActionPerformed(evt);
            }
        });

        btnDodajAutora.setText("Dodaj");
        btnDodajAutora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajAutoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImePrezimeAutora, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPretraziAutore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrikaziSveAutore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDodajAutora)
                        .addGap(0, 129, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtImePrezimeAutora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraziAutore)
                    .addComponent(btnPrikaziSveAutore)
                    .addComponent(btnDodajAutora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Dodati autori"));

        tabelaDodatiAutori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tabelaDodatiAutori);

        btnIzbaciAutora.setText("Izbaci");
        btnIzbaciAutora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbaciAutoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnIzbaciAutora)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIzbaciAutora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtGodina)))
                        .addGap(18, 18, 18)
                        .addComponent(btnSacuvaj)
                        .addGap(18, 18, 18)
                        .addComponent(btnNazad))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnNazad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(472, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1447, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        KontrolerKlijent.getInstance().prikaziGlavnuKlijentFormu("unosReferenceForma");
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnPretraziNastavnikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziNastavnikeActionPerformed
        String imePrezime = txtImePrezimeNastavnika.getText();
        KontrolerKlijent.getInstance().pretraziNastavnike(imePrezime);
    }//GEN-LAST:event_btnPretraziNastavnikeActionPerformed

    private void btnPrikaziSveNastavnikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziSveNastavnikeActionPerformed
        KontrolerKlijent.getInstance().pretraziNastavnike("");
    }//GEN-LAST:event_btnPrikaziSveNastavnikeActionPerformed

    private void btnDodajNastavnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajNastavnikaActionPerformed
        int row = tabelaPretragaNastavnika.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Morate izabrati nastavnika!");
        } else {
            Nastavnik n = listaNastavnikaPretraga.get(row);
            if (!sadrzinastavnika(n)) {
                referenca.getListaNastavnika().add(n);
                osveziTabele();
            } else {
                JOptionPane.showMessageDialog(this, "Nastavnik je vec dodat!");
            }

        }
    }//GEN-LAST:event_btnDodajNastavnikaActionPerformed

    private void btnIzbaciNastavnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbaciNastavnikaActionPerformed
        int row = tabelaDodatiNastavnici.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Morate izabrati nastavnika!");
        } else {
            referenca.getListaNastavnika().remove(row);
            osveziTabele();
        }
    }//GEN-LAST:event_btnIzbaciNastavnikaActionPerformed

    private void btnPretraziAutoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziAutoreActionPerformed
        String imePrezime = txtImePrezimeAutora.getText();
        KontrolerKlijent.getInstance().pretraziAutore(imePrezime);
    }//GEN-LAST:event_btnPretraziAutoreActionPerformed

    private void btnPrikaziSveAutoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziSveAutoreActionPerformed
        KontrolerKlijent.getInstance().pretraziAutore("");
    }//GEN-LAST:event_btnPrikaziSveAutoreActionPerformed

    private void btnDodajAutoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajAutoraActionPerformed
        int row = tabelaPretragaAutora.getSelectedRow();
        
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Morate izabrati autora!");
        } else {
            SpoljniAutor sa = listaAutoraPretraga.get(row);
            if (!sadrziAutora(sa)) {
                referenca.getListaSpoljnihAutora().add(sa);
                osveziTabele();
            } else {
                JOptionPane.showMessageDialog(this, "Autor je vec dodat!");
            }
        }
    }//GEN-LAST:event_btnDodajAutoraActionPerformed

    private void btnIzbaciAutoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbaciAutoraActionPerformed
        int row = tabelaDodatiAutori.getSelectedRow();
        
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Morate izabrati autora!");
        } else {
            referenca.getListaSpoljnihAutora().remove(row);
            osveziTabele();
        }
    }//GEN-LAST:event_btnIzbaciAutoraActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        String naslov = txtNaslov.getText();
        String godinaString = txtGodina.getText();
        int godina = 0;
        try {
            godina = Integer.parseInt(godinaString);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Godina mora biti broj!");
            return;
        }
        
        referenca.setNaslov(naslov);
        referenca.setGodina(godina);
        KontrolerKlijent.getInstance().unesiReferencu(referenca);
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnosNoveReferenceForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnosNoveReferenceForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnosNoveReferenceForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnosNoveReferenceForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnosNoveReferenceForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajAutora;
    private javax.swing.JButton btnDodajNastavnika;
    private javax.swing.JButton btnIzbaciAutora;
    private javax.swing.JButton btnIzbaciNastavnika;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnPretraziAutore;
    private javax.swing.JButton btnPretraziNastavnike;
    private javax.swing.JButton btnPrikaziSveAutore;
    private javax.swing.JButton btnPrikaziSveNastavnike;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tabelaDodatiAutori;
    private javax.swing.JTable tabelaDodatiNastavnici;
    private javax.swing.JTable tabelaPretragaAutora;
    private javax.swing.JTable tabelaPretragaNastavnika;
    private javax.swing.JTextField txtGodina;
    private javax.swing.JTextField txtImePrezimeAutora;
    private javax.swing.JTextField txtImePrezimeNastavnika;
    private javax.swing.JTextField txtNaslov;
    // End of variables declaration//GEN-END:variables

    public void osveziTabele() {
        ModelTabelePretragaNastavnik mtpn1 = (ModelTabelePretragaNastavnik) tabelaPretragaNastavnika.getModel();
        mtpn1.fireTableDataChanged();

        ModelTabelePretragaNastavnik mtpn2 = (ModelTabelePretragaNastavnik) tabelaDodatiNastavnici.getModel();
        mtpn2.fireTableDataChanged();

        ModelTabeleSpoljniAutor mtsa1 = (ModelTabeleSpoljniAutor) tabelaPretragaAutora.getModel();
        mtsa1.fireTableDataChanged();

        ModelTabeleSpoljniAutor mtsa2 = (ModelTabeleSpoljniAutor) tabelaDodatiAutori.getModel();
        mtsa2.fireTableDataChanged();
    }

    private void inicijalizujListe() {
        listaAutoraPretraga = new ArrayList<>();
        listaNastavnikaPretraga = new ArrayList<>();
    }

    private void inicijalizujTabele() {
        ModelTabelePretragaNastavnik mtpn1 = new ModelTabelePretragaNastavnik();
        mtpn1.setForma("unosReferenceFormaPretraga");
        tabelaPretragaNastavnika.setModel(mtpn1);

        ModelTabelePretragaNastavnik mtpn2 = new ModelTabelePretragaNastavnik();
        mtpn2.setForma("unosReferenceFormaReferenca");
        tabelaDodatiNastavnici.setModel(mtpn2);

        ModelTabeleSpoljniAutor mtsa1 = new ModelTabeleSpoljniAutor();
        mtsa1.setForma("unosReferenceFormaPretraga");
        tabelaPretragaAutora.setModel(mtsa1);

        ModelTabeleSpoljniAutor mtsa2 = new ModelTabeleSpoljniAutor();
        mtsa2.setForma("unosReferenceFormaReferenca");
        tabelaDodatiAutori.setModel(mtsa2);

    }

    private boolean sadrzinastavnika(Nastavnik n) {
        for (Nastavnik nastavnik : referenca.getListaNastavnika()) {
            if (nastavnik.getNastavnikID() == n.getNastavnikID()) {
                return true;
            }
        }
        return false;
    }

    private boolean sadrziAutora(SpoljniAutor sa) {
        for (SpoljniAutor spa : referenca.getListaSpoljnihAutora()) {
            if (spa.getAutorID() == sa.getAutorID()) {
                return true;
            }
        }
        return false;
    }

    public void uspesnoUnetaReferenca(boolean uspesnoUnetaReferenca) {
        if (uspesnoUnetaReferenca) {
            JOptionPane.showMessageDialog(this, "Uspesno uneta referenca u bazu!");
        } else {
            JOptionPane.showMessageDialog(this, "Greska prilikom unosa reference u bazu!");
        }
    }
}
